### ISSUE TITLE
$ ros2 launch igus_rebel_description_ros2 visualize.launch.py load_gazebo:=true

### ISSUE THREAD

**Issue by Yushuo001A** [AIRLab-POLIMI/BTGenBot#10]
When starting gazebo simulation, the following error message appears. Is the simulation file description in the source code incorrect?
![image](https://github.com/AIRLab-POLIMI/BTGenBot/assets/139625666/0b2e2256-1365-4a3a-9df3-c367f97039b2)

**Comment by RiccardoIzzo** [comment]
Hi, since I never used the command `ros2 launch igus_rebel_description_ros2 visualize.launch.py load_gazebo:=true` I'm not familiar with this error. Why do you need that command? The launch files in `igus_rebel_commander` are enough to correctly load the simulation win Gazebo. Nevertheless, I suggest you to open an issue in the correct repository [ros2-igus-rebel](https://github.com/AIRLab-POLIMI/ros2-igus-rebel) for further information.
